### ISSUE TITLE
lundi

### ISSUE THREAD

**Issue by edernlehyaric** [vxid/partiels#1]

**Comment by edernlehyaric** [comment]
et pour f2 on aura 1/2 + 1/4 + 1/8 => tend vers 1

**Comment by edernlehyaric** [comment]
maxime, j'ai du permission denied pour push sur ce repo ? tu dois ajouter des users non ?

**Comment by vxid** [comment]
C'est fait normalement.

**Comment by edernlehyaric** [comment]
yep nickel

**Comment by vxid** [comment]
Et si possible ça serait bien d'avoir un fichier en markdown par sujet et d'ouvrir des issues pour chaque exo/problème spécifique. Ca sera plus clair.

**Comment by ColineUVSQ** [comment]
J'arrive après la bataille je crois ^^

**Comment by edernlehyaric** [comment]
"fichier en markdown" tu surrestimes ma volonté de faire ça proprement.
Sinon pour l'exemple de du réseau de serveurs en anneau, avec le tableau des Ni en fonction de K. on avait pas remplie la ligne K=4, perso je trouve N1 = 64/99 = N2 = N3, N4= 68/33
vous avez la même chose ?

**Comment by ColineUVSQ** [comment]
Pas fait encore, je vais essayer

**Comment by ColineUVSQ** [comment]
Je trouve pareil

**Comment by ColineUVSQ** [comment]
J'ai fait l'exo 4 du partiel de 2015 session 2 : 
On a une matrice M = (0 0.5 0.5 0
                                    1  0   0    0
                                     0  0  0    1
                                     1  0   0    0)
1. Il faut dire si la matrice est irréductible : 
Oui, c'est le cas. Parce que le graphe correspondant est fortement connexe. On le prouve en dessinant le graphe, et en disant qu'à partir d'un sommet x quelconque il existe un chemin pour aller à tous les autres (arborescence) et à partir de n'importe quel sommet du graphe, il existe un chemin pour aller au sommet x (anti-arborescence). Et je crois que ça prouve la forte connexité :)

2. Il faut dire si elle est apériodique
En dessinant le graphe, on voit qu'il y a 2 cycles, un de taille 2 et un de taille 3. Comme pgcd(2,3) = 1, la matrice est apériodique.

3. Il faut dire si elle admet une mesure stationnaire, et si oui, la calculer
Comme la matrice est irréductible, irréductible, et finie, elle admet une mesure stationnaire pi, qui vérifie l'équation pi*M = pi (avec aussi, somme des pi = 1). En résolvant le système, on trouve : pi1 = 2/5, et pi2 = pi3 = pi4 = 1/5

**Comment by ColineUVSQ** [comment]
Bintou n'a pas reçu d'invitation pour le repo, je sais pas si c'est normal ?

**Comment by edernlehyaric** [comment]
what tu as eu cet examen où ? je ne le trouve pas dans le pdf que bintou a filé

**Comment by edernlehyaric** [comment]
En tout cas, tes resultats sont bons

**Comment by ColineUVSQ** [comment]
Ah oui, c'est vrai, c'est dans le premier pdf que Bintou m'avait envoyé. Je vous le mets dans le répertoire "lundi"

**Comment by edernlehyaric** [comment]
y'a une mafia des sujets d'examens, incroyable

**Comment by ColineUVSQ** [comment]
:) je l'envoie par mail, finalement

**Comment by edernlehyaric** [comment]
l'exercice 2, c'est la même preuve que ce que j'avais fait dans l'exercice 4 de session 2 2016, monotone * anti-monotone = anti-m, mono * mono = mono

**Comment by edernlehyaric** [comment]
aprés l'exercice 3 est équivalent à l'exo 1 de 2016, et j'aimerai vraiment savoir ce qu'il entend par "décomposition en évt monotones"
meme si encore une fois l'exam sera pas du tout pareil, je suis curieux !

**Comment by BintouFOFANA** [comment]
lol @edernlehyaric  Coline est ma puce, lol je rigole
au fait je ne vous l'ai pas envoyé parce qu'il était mal scanné et c'est pratiquement les mêmes sujets

**Comment by vxid** [comment]
Question rapide @edernlehyaric pour les probas de retour.

On a pas plutôt f(1,1) = 1/3, f(1,2) = 1/9 et donc f1 = (1/3)^n -> 0 ?

**Comment by edernlehyaric** [comment]
@vxid Je vois pas de quelle chaine tu parles ?
