### ISSUE TITLE
Simulation : Réseau ouvert - réseau fermé

### ISSUE THREAD

**Issue by BintouFOFANA** [vxid/partiels#2]
Svp vous avez compris cette partie du cours de simul sur les réseaux ouverts ?

**Comment by ColineUVSQ** [comment]
Moi, j'ai juste compris que les réseaux ouverts c'était le théorème de Jackson, et les réseaux fermés le théorème de Gordon :).  Je pense pas qu'il nous redemanderait les preuves de toute façon. Je sais pas trop quel type d'exercice on peut avoir là-dessus. Peut-être sur l'algo MVA comme on a vu en cours...

**Comment by vxid** [comment]
Est-ce que l'un(e) d'entre vous pourrait m'envoyer la partie du cours qui correspond à Gordon/Jackdon et MVA en photo? Merciii

**Comment by edernlehyaric** [comment]
https://imgur.com/a/nUy76
je crois que y'a tout ici

**Comment by vxid** [comment]
Merci tu gères!

**Comment by BintouFOFANA** [comment]
Bonjour à tous
dans l'exemple sur l'algo de Jackson, dans le 3ieme terme pourquoi es ce qu'on a x2 - 1?

**Comment by BintouFOFANA** [comment]
@edernlehyaric  j'ai jeté un coup d'œil au doc que tu as envoyé à Max dans la formule de Pasta 
on pas écris les mêmes choses

**Comment by vxid** [comment]
Est-ce qu'on aura besoin d'autre chose que l'algo MVI honnêtement? J'ai pas l'impression.

**Comment by BintouFOFANA** [comment]
Peut-être mais quand je vérifie j'aimerais avoir les mêmes formules que les autres

**Comment by edernlehyaric** [comment]
algo jasckon/mva, kesako ?
@BintouFOFANA tu as écrit quoi pour la formule de pasta ?

**Comment by vxid** [comment]
En gros MVA c'est juste l'algo itératif de calcul en circuit fermé (si j'ai bien compris).

C'est facilement calculable et donc plus adapté au format exam (il a fait la même l'année dernière en M1, que des quesitons relativement sipmle à calculer , le reste c'était trop chaud).

**Comment by BintouFOFANA** [comment]
Pour l'algo MVA c'est pas compliqué, j'espère qu'il fera comme en M1 des choses faciles à appliquer comme tu l'as dit

**Comment by edernlehyaric** [comment]
Vous avez un exemple simple pour vous chère Edern ?

**Comment by vxid** [comment]
Dans les docs que tu m'as envoyé. Les phases de calcul pour K=1, puis K=2 etc

**Comment by edernlehyaric** [comment]
ah ok merci !

**Comment by ColineUVSQ** [comment]
Salut, désolée de répondre tard 
@BintouFOFANA  Pour ta question sur l'exemple du théorème de Jackson, je crois qu'on met pi(X1+1, X2-1) parce que c'est le cas du routage, pour des paquets qui quittent la file 1 pour aller dans la file 2.

**Comment by BintouFOFANA** [comment]
merci ma puce
