### ISSUE TITLE
mardi

### ISSUE THREAD

**Issue by edernlehyaric** [vxid/partiels#3]
Salut, vous avez fait le sujet de mars 2017 d'algo ?

**Comment by ColineUVSQ** [comment]
Je suis en train de le faire. Le début, ça va, mais la fin, c'est un peu dur, je trouve.

**Comment by ColineUVSQ** [comment]
Tu as trouvé les bornes de la question 7 ?

**Comment by edernlehyaric** [comment]
non absolument pas tester de faire ce sujet ! il mefait un peu peur

**Comment by ColineUVSQ** [comment]
Jusqu'à la question 6, ça ressemble à celui de l'année dernière. Après, c'est moins marrant.

**Comment by edernlehyaric** [comment]
On est d'accord que le nombre chromatique c'est aussi l'ordre de la clique max du graphe ?

**Comment by edernlehyaric** [comment]
et on sait aussi que l'ordre de stablemax(G) = ordre de cliquemax(inverse(G))

**Comment by edernlehyaric** [comment]
je sais pas si ça mène quelque part mais je connais pas d'autres relations entre chro/stable/clique

**Comment by ColineUVSQ** [comment]
Je suis d'accord, mais j'arrive quand même pas trop à trouver la borne inf de stable(G) en fonction du degré max. Stable(G) = clique(inverse(G)) ne nous donne pas vraiment de relation sur la clique de G. Du coup, pour passer au nombre chromatique... sinon je pensais à nombre de sommets/nombre de chromatique pour la borne inf, mais je sais pas si ça marche dans tous les cas

**Comment by ColineUVSQ** [comment]
En fait, je voulais dire la borne inf de stable(g) en fonction du nbre chromatique, pas le degré max

**Comment by edernlehyaric** [comment]
on peut déduire des stables à partir d'une coloration => où chaque stable serait l'ensemble des noeuds d'une même couleur. Dans le pire des cas, le stable le plus grand sera de taille ordre(G)(nb de sommets) / X(G),  du coup je crois que tu as raison

**Comment by edernlehyaric** [comment]
dans la question 5 il demande de "prouver" le nombre chromatique. Moi je dirais simplement que la clique de taille maximale a trois sommets, mais ça suffit pas non ?

**Comment by edernlehyaric** [comment]
pour b), à part dire que dans le meilleur cas, le graphe a une clique de taille n1 et n2 composantes non connexes tq n1 +n2 = n, du coup, |stable| <= n - |clique|, sinon je vois pas
c) χ(G) >= |stable|; degG + 1 >= χ(G) 
=> degG >= |stable|- 1

**Comment by ColineUVSQ** [comment]
Pour la 5, je pense qu'on peut dire que comme le graphe est planaire, son nombre chromatique est inférieur à 4, et comme il y a une clique de taille 4, son nombre chromatique est 4.

**Comment by ColineUVSQ** [comment]
Pour la c) tu donnes une borne inférieure du degré max, non ?

**Comment by edernlehyaric** [comment]
Bien vu pour la propriété sur les graphes planaires

**Comment by BintouFOFANA** [comment]
ce que moi j'ai fait:
le graphe contient un cycle de longueur impaire donc X(G) >=  3
G contient une clique de taille 4 donc X(G) <= 4
donc X(G)=4

@ColineUVSQ , sauf erreur de ma part je pense qu'on a dit qu'un graphe planaire est au plus 5-coloriable

**Comment by edernlehyaric** [comment]
X(g) >= clique(G) et non X(G) <= clique(G)
exemple : un anneau de taille 5 : X(G) = 3, clique(G) = 2

**Comment by BintouFOFANA** [comment]
oui je vois mon erreur merci

**Comment by BintouFOFANA** [comment]
Sinon tu as fait la partie de l'exam sur le Dom(G)?

**Comment by edernlehyaric** [comment]
non j'avais pas envie de me choper un mal de crâne

**Comment by BintouFOFANA** [comment]
Non ne dit pas ça on peur essayer et comparer les résultats.
On aura forcement un truc pareil

**Comment by BintouFOFANA** [comment]
tu trouves le Dom du graphe donné?

**Comment by edernlehyaric** [comment]
10) 2

**Comment by BintouFOFANA** [comment]
Le dom(G)=2

**Comment by BintouFOFANA** [comment]
On remarque le graphe contient  un rectangle soit tu prends les 2 sommets du haut , soit  ceux du bas. Parce que chaque sommet est à distance 1 de chacun de ces sommets 
Je sais si je m'explique comme il faut

**Comment by edernlehyaric** [comment]
il demande pas de preuve donc osef, au pire juste dessine le graphe avec tes choix de V'

**Comment by BintouFOFANA** [comment]
pourquoi tu dis 10.2?

**Comment by edernlehyaric** [comment]
j'avais écrit "10) 2" mais github a formaté ça !

**Comment by BintouFOFANA** [comment]
lol ok

**Comment by BintouFOFANA** [comment]
explique et réponds à certaines question de l'exam
[https://liris.cnrs.fr/~aparreau/Research/Slides/seminaireENS.pdf](url)

**Comment by edernlehyaric** [comment]
"11) |dom(G)| >= n / (1+∆)

**Comment by ColineUVSQ** [comment]
@BintouFOFANA Pour les graphes planaires, il y a le théorème des 4 couleurs qui dit qu'on peut colorier un graphe planaire avec 4 couleurs au plus, mais il n'est pas encore bien prouvé ou un truc comme ça... Du coup, c'est vrai, je sais pas si on peut l'utiliser :). Dans tous les cas, ta preuve marche hyper bien :)

**Comment by ColineUVSQ** [comment]
@edernlehyaric Suis d'accord pour la borne inf de dom(G) en fonction du degré max

**Comment by ColineUVSQ** [comment]
Quelqu'un a une réponse à la question 9 de ce partiel ? (rattrapage mars 2017) Quand il demande un graphe biparti tel que Max(|V1|, |V2|) < Stable(G)

**Comment by edernlehyaric** [comment]
si je dis pas de conneries : exemple max <
tu fais fais relier tous les sommets de V1 a un sommet unique de V2, tous les sommets de V2 à un sommet unique de V1, et ça fait un stable de taille |V1| + |V2| - 2

**Comment by ColineUVSQ** [comment]
Ah ok :) Merci !

**Comment by BintouFOFANA** [comment]
dessiner le graphe suffirait?

**Comment by BintouFOFANA** [comment]
@vxid la question 5 de l'exam de l'année dernière, j'ai vu dans le doc que tu m'as donné que tu as pensé à une récurrence moi j'avais pensé au théorème des tiroirs

**Comment by vxid** [comment]
Oui, théorème des tiroirs. C'est axactement ce que j'ai mis.

@edernlehyaric Pour la q 5 il demande juste de montrer qu'un tel graph existe. Je me suis pas pris la tête et j'ai montré que k5 marchait, et qu'après tu rejoutes juste une chaine de longueur n-5 qui part d'un des sommets. Ca suffit pour montrer qu'il existe un graphe 5-coloriable pour tot n >= 5

**Comment by vxid** [comment]
Btw




[network-algorithmics.pdf](https://github.com/vxid/partiels/files/1549312/network-algorithmics.pdf)
[game-theory.pdf](https://github.com/vxid/partiels/files/1549313/game-theory.pdf)
[distributed-algorithmics.pdf](https://github.com/vxid/partiels/files/1549314/distributed-algorithmics.pdf)
[data-networks.pdf](https://github.com/vxid/partiels/files/1549315/data-networks.pdf)

**Comment by vxid** [comment]
N'hésitez pas si vous voyez des erreurs, il y en a certainement...

**Comment by vxid** [comment]
@ColineUVSQ @edernlehyaric 

Vous la trouvez comment la borne inf de dom(G) ?

**Comment by BintouFOFANA** [comment]
moi je me dit que un sommet peut dominer au maximum DegreMax de G et on a n sommets  donc je fais  n/DegreMax +1 au cas ou on un sommet

**Comment by BintouFOFANA** [comment]
et dans ton cours des graphes tu as mis tout graphe planaire est 4-coloriable  je suis pas vraiment d'accord parce K3 n'est pas 4-coloriable. Je pense plutôt que c'est le théorème des 4 couleurs (un graphe qu'on peut coupé en plusieurs régions connexe est au plus 4-coloriable) est  applicable aux cartes ( en donc aux graphes planaires) comme @ColineUVSQ  l'avait dit

**Comment by BintouFOFANA** [comment]
désolée de répondre si tard

**Comment by ColineUVSQ** [comment]
D'accord avec tout ça :)

**Comment by vxid** [comment]
Oui exact. Donc khi(G) <= 4 si G est planaire du coup

**Comment by BintouFOFANA** [comment]
oui
