### ISSUE TITLE
jejejeeudi

### ISSUE THREAD

**Issue by edernlehyaric** [vxid/partiels#4]

**Comment by edernlehyaric** [comment]
me too thanks

**Comment by vxid** [comment]
![flat 800x800 075 f](https://user-images.githubusercontent.com/16440823/33905295-76999536-df7e-11e7-8f99-8c6ab3e67ef0.jpg)

**Comment by edernlehyaric** [comment]
l'histoire de comment on a eu 5/20 en algo distribué

**Comment by BintouFOFANA** [comment]
dites moi que vous révisez à fond pour que j'ai la motivation

**Comment by vxid** [comment]
Pas commencé mdr

**Comment by vxid** [comment]
Mais francehement c'est simple une fois qu'on connait l'algo de Chang-Hart-Koenemann-Robert-Zarichvilli-McThompson-Nash

**Comment by ColineUVSQ** [comment]
Je comprends pas tout de vos délires respectifs, mais c'est pas grave :). Je me joins un peu à la perte de motivation générale... Je trouve que les sujets d'exam sont déprimants,  soit c'est des trucs qu'on n'a pas vu, soit je comprends même pas les questions :p. Quelqu'un a fait celui avec le tore ?

**Comment by edernlehyaric** [comment]
me suis levé à 9h, apres une courte nuit, j'ai regardé l'exo 1 je me suis recouché , reveil 15h. ma volonté est à 0

**Comment by BintouFOFANA** [comment]
pouvez vous me passer l'énoncé du td4 svp?

**Comment by BintouFOFANA** [comment]
@ColineUVSQ je n'ai pas faire le tore, je veux dire que je n'ai encore rien fait lol, mais je compte traiter un sujet d'examen ce soir,

**Comment by ColineUVSQ** [comment]
Le TD4, c'est celui avec l'exercice bizarre, où la prof nous avait donné une correction qui avait l'air fausse ?

**Comment by BintouFOFANA** [comment]
oui c'est cela lol

**Comment by ColineUVSQ** [comment]
Je viens de le mettre sur le repo :). La photocopie n'est pas terrible, désolée...
Bon courage pour les sujets d'exam :)

**Comment by BintouFOFANA** [comment]
merci
Pour les examens je vais essayer

**Comment by BintouFOFANA** [comment]
Dans le td3, 
Quand on dit le site 3 diffère à cause du site 4, ça veut qu'il met le site 4 dans son tableau différé?

**Comment by BintouFOFANA** [comment]
Je pense que j'ai compris

**Comment by edernlehyaric** [comment]
http://botnik.org/content/harry-potter.html pas aussi instructif que les revisions, mais tout aussi bon

**Comment by ColineUVSQ** [comment]
@BintouFOFANA  Je pense que c'est le site 4 qui met le site 3 dans son tableau différé, si le site 3 diffère à cause du site 4

**Comment by BintouFOFANA** [comment]
@ColineUVSQ , je pense que au td la prof avait dit de comparer les valeurs d'estampille des 2 sites (pour la question5) et celui qui avait la plus petite valeur différait à cause de l'autre.
Et dans l'algo quand un site compare les valeurs d'estampille s'il a la plus petite valeur il dit qu'il est prioritaire et met l'autre site dans son tableau différé

**Comment by ColineUVSQ** [comment]
Oui, oui, je suis d'accord. Du coup, celui qui a la plus petite valeur est prioritaire et c'est l'autre qui "diffère", au sens où il doit attendre.

**Comment by BintouFOFANA** [comment]
ok merci

**Comment by edernlehyaric** [comment]
tsss la façon de coder du mec est dégueulasse 
tant que vrai {
   recevoir jeton
    envoyer jeton
}

ça veut rien dire

**Comment by vxid** [comment]
Image donner le bon algo mais avoir 0 parce que le pseudo-code compile pas.
